[project]
name = "tndforcop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.2.6",
    "pandas>=2.3.1",
    "pygam>=0.10.1",
    "scikit-learn>=1.7.1",
    "scipy>=1.15.3",
]
